### ISSUE TITLE
hover subtle zoom effects on buttons

### ISSUE THREAD

**Issue by deepbeatz** [Sukrittt/Limetta#2]
@Sukrittt @sukrit101 assign me this issue under apertre

**Comment by Sukrittt** [comment]
Attach screenshots explaining this issue.

**Comment by deepbeatz** [comment]
the problem is that i am nit being able to run the website in my local server......everything is showing error.....

**Comment by Sukrittt** [comment]
Have you added all the necessary .env variables?

**Comment by deepbeatz** [comment]
no, sorry, where and what to add in the .env file? @Sukrittt

**Comment by deepbeatz** [comment]
i created the .env file using command 
cp .env.example .env

but after that?

**Comment by Sukrittt** [comment]
In this [file](https://github.com/Sukrittt/Limetta/blob/main/.env.example), appropriate comments are mentioned for each env variable required. Kindly refer to it.

**Comment by Sukrittt** [comment]
Can you explain the issue?
